syntax = "proto3";

package sergeypopov83.chariot.processing.operations.grpc;

import "google/protobuf/timestamp.proto";
import "google/type/money.proto";

service OperationsGrpcService {
    rpc OperationsPeriodStatisticsByLegalEntity (OperationsPeriodStatisticsByLegalEntityRequest) returns (OperationsPeriodStatisticsByLegalEntityResponse);
    //    rpc OperationsPeriodStatistics();
    rpc LastNOperations (LastNOperationsRequest) returns (LastNOperationsResponse);
    rpc TopNOperationsByAmount (TopNOperationsByAmountRequest) returns (TopNOperationsByAmountResponse);
}

message OperationsPeriodStatisticsByLegalEntityRequest {
    string legal_entity = 1;
    google.protobuf.Timestamp period_start = 2;
    google.protobuf.Timestamp period_end = 3;
}

message OperationsPeriodStatisticsByLegalEntityResponse {
    // account id to statistics map
    string legal_entity = 1;
    google.protobuf.Timestamp period_start = 2;
    google.protobuf.Timestamp period_end = 3;
    map<string, OperationsStatisticsByStatus> statistics = 4;
}

enum AccountTypes {
    ACCOUNT_TYPES_UNKNOWN = 0;
    ACCOUNT_TYPES_CREDIT = 1;
    ACCOUNT_TYPES_DEBIT = 2;
}

message OperationsStatisticsByStatus {
    map<string, OperationsPeriodStatistics> statistics = 1;
}

message OperationsPeriodStatistics {
    int64 count = 1;
    google.type.Money debit_sum = 2;
    google.type.Money credit_sum = 3;
    google.type.Money current_amount = 4;
    AccountTypes account_type = 5;
    string status = 6;
}

message LastNOperationsResponse {
    repeated Operation operations = 1;
}

message Operation {
    string operation_id = 1;
    string operation_type = 2;
    string status = 3;
    google.protobuf.Timestamp created_at = 4;
    google.type.Money amount = 5;
    string account_id = 6;
    string legal_entity_id = 7;
}

message LastNOperationsRequest {
    int32 operations_count = 1;
}

message TopNOperationsByAmountRequest {
    int32 operations_count = 1;
}

message TopNOperationsByAmountResponse {
    repeated Operation operations = 1;
}