apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: {{ .Release.Namespace }}
  labels:
    app: operationspresenter
data:
  MONGO_HOST: {{ .Values.db.mongo.host }}
  MONGO_USER: {{ .Values.db.mongo.user }}